spring:
  application:
    name: trabalho-poo-ads4a
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/db.changelog-master.yml
    test-rollback-on-update: false

api:
  security:
    token:
      secret: ${JWT_TOKEN_KEY}